//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TastyChef.TastyChefNutritionAssessmentWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TastyChefNutritionAssessmentWS.NutritionAssessmentSoap")]
    public interface NutritionAssessmentSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMI", ReplyAction="*")]
        decimal CalculateBMI(decimal h, decimal w);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMI", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> CalculateBMIAsync(decimal h, decimal w);
        
        // CODEGEN: Generating message contract since element name weightstatusResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/weightstatus", ReplyAction="*")]
        TastyChef.TastyChefNutritionAssessmentWS.weightstatusResponse weightstatus(TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/weightstatus", ReplyAction="*")]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.weightstatusResponse> weightstatusAsync(TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequest request);
        
        // CODEGEN: Generating message contract since element name gender from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMR", ReplyAction="*")]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRResponse CalculateBMR(TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBMR", ReplyAction="*")]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRResponse> CalculateBMRAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequest request);
        
        // CODEGEN: Generating message contract since element name weightstatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCalories", ReplyAction="*")]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesResponse CalculateCalories(TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCalories", ReplyAction="*")]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesResponse> CalculateCaloriesAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequest request);
        
        // CODEGEN: Generating message contract since element name weightstatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/levelCarbohydrate", ReplyAction="*")]
        TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateResponse levelCarbohydrate(TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/levelCarbohydrate", ReplyAction="*")]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateResponse> levelCarbohydrateAsync(TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequest request);
        
        // CODEGEN: Generating message contract since element name level from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateProteinRange", ReplyAction="*")]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeResponse CalculateProteinRange(TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateProteinRange", ReplyAction="*")]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeResponse> CalculateProteinRangeAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequest request);
        
        // CODEGEN: Generating message contract since element name level from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCarbohydrateRange", ReplyAction="*")]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeResponse CalculateCarbohydrateRange(TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCarbohydrateRange", ReplyAction="*")]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeResponse> CalculateCarbohydrateRangeAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequest request);
        
        // CODEGEN: Generating message contract since element name level from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateFatRange", ReplyAction="*")]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeResponse CalculateFatRange(TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateFatRange", ReplyAction="*")]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeResponse> CalculateFatRangeAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateProtein", ReplyAction="*")]
        decimal CalculateProtein(decimal calories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateProtein", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> CalculateProteinAsync(decimal calories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateFats", ReplyAction="*")]
        decimal CalculateFats(decimal calories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateFats", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> CalculateFatsAsync(decimal calories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCarbohydrate", ReplyAction="*")]
        decimal CalculateCarbohydrate(decimal calories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCarbohydrate", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> CalculateCarbohydrateAsync(decimal calories);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class weightstatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="weightstatus", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequestBody Body;
        
        public weightstatusRequest() {
        }
        
        public weightstatusRequest(TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class weightstatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal bmi;
        
        public weightstatusRequestBody() {
        }
        
        public weightstatusRequestBody(decimal bmi) {
            this.bmi = bmi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class weightstatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="weightstatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.weightstatusResponseBody Body;
        
        public weightstatusResponse() {
        }
        
        public weightstatusResponse(TastyChef.TastyChefNutritionAssessmentWS.weightstatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class weightstatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string weightstatusResult;
        
        public weightstatusResponseBody() {
        }
        
        public weightstatusResponseBody(string weightstatusResult) {
            this.weightstatusResult = weightstatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateBMRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateBMR", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequestBody Body;
        
        public CalculateBMRRequest() {
        }
        
        public CalculateBMRRequest(TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateBMRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal h;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal w;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gender;
        
        public CalculateBMRRequestBody() {
        }
        
        public CalculateBMRRequestBody(decimal h, decimal w, int age, string gender) {
            this.h = h;
            this.w = w;
            this.age = age;
            this.gender = gender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateBMRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateBMRResponse", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRResponseBody Body;
        
        public CalculateBMRResponse() {
        }
        
        public CalculateBMRResponse(TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateBMRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal CalculateBMRResult;
        
        public CalculateBMRResponseBody() {
        }
        
        public CalculateBMRResponseBody(decimal CalculateBMRResult) {
            this.CalculateBMRResult = CalculateBMRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateCaloriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateCalories", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequestBody Body;
        
        public CalculateCaloriesRequest() {
        }
        
        public CalculateCaloriesRequest(TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateCaloriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal bmr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal activity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string weightstatus;
        
        public CalculateCaloriesRequestBody() {
        }
        
        public CalculateCaloriesRequestBody(decimal bmr, decimal activity, string weightstatus) {
            this.bmr = bmr;
            this.activity = activity;
            this.weightstatus = weightstatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateCaloriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateCaloriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesResponseBody Body;
        
        public CalculateCaloriesResponse() {
        }
        
        public CalculateCaloriesResponse(TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateCaloriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal CalculateCaloriesResult;
        
        public CalculateCaloriesResponseBody() {
        }
        
        public CalculateCaloriesResponseBody(decimal CalculateCaloriesResult) {
            this.CalculateCaloriesResult = CalculateCaloriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class levelCarbohydrateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="levelCarbohydrate", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequestBody Body;
        
        public levelCarbohydrateRequest() {
        }
        
        public levelCarbohydrateRequest(TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class levelCarbohydrateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string weightstatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string medical;
        
        public levelCarbohydrateRequestBody() {
        }
        
        public levelCarbohydrateRequestBody(string weightstatus, string medical) {
            this.weightstatus = weightstatus;
            this.medical = medical;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class levelCarbohydrateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="levelCarbohydrateResponse", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateResponseBody Body;
        
        public levelCarbohydrateResponse() {
        }
        
        public levelCarbohydrateResponse(TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class levelCarbohydrateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string levelCarbohydrateResult;
        
        public levelCarbohydrateResponseBody() {
        }
        
        public levelCarbohydrateResponseBody(string levelCarbohydrateResult) {
            this.levelCarbohydrateResult = levelCarbohydrateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateProteinRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateProteinRange", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequestBody Body;
        
        public CalculateProteinRangeRequest() {
        }
        
        public CalculateProteinRangeRequest(TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateProteinRangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string level;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal calories;
        
        public CalculateProteinRangeRequestBody() {
        }
        
        public CalculateProteinRangeRequestBody(string level, decimal calories) {
            this.level = level;
            this.calories = calories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateProteinRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateProteinRangeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeResponseBody Body;
        
        public CalculateProteinRangeResponse() {
        }
        
        public CalculateProteinRangeResponse(TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateProteinRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateProteinRangeResult;
        
        public CalculateProteinRangeResponseBody() {
        }
        
        public CalculateProteinRangeResponseBody(string CalculateProteinRangeResult) {
            this.CalculateProteinRangeResult = CalculateProteinRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateCarbohydrateRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateCarbohydrateRange", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequestBody Body;
        
        public CalculateCarbohydrateRangeRequest() {
        }
        
        public CalculateCarbohydrateRangeRequest(TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateCarbohydrateRangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string level;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal calories;
        
        public CalculateCarbohydrateRangeRequestBody() {
        }
        
        public CalculateCarbohydrateRangeRequestBody(string level, decimal calories) {
            this.level = level;
            this.calories = calories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateCarbohydrateRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateCarbohydrateRangeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeResponseBody Body;
        
        public CalculateCarbohydrateRangeResponse() {
        }
        
        public CalculateCarbohydrateRangeResponse(TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateCarbohydrateRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateCarbohydrateRangeResult;
        
        public CalculateCarbohydrateRangeResponseBody() {
        }
        
        public CalculateCarbohydrateRangeResponseBody(string CalculateCarbohydrateRangeResult) {
            this.CalculateCarbohydrateRangeResult = CalculateCarbohydrateRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateFatRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateFatRange", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequestBody Body;
        
        public CalculateFatRangeRequest() {
        }
        
        public CalculateFatRangeRequest(TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateFatRangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string level;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal calories;
        
        public CalculateFatRangeRequestBody() {
        }
        
        public CalculateFatRangeRequestBody(string level, decimal calories) {
            this.level = level;
            this.calories = calories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateFatRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateFatRangeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeResponseBody Body;
        
        public CalculateFatRangeResponse() {
        }
        
        public CalculateFatRangeResponse(TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateFatRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateFatRangeResult;
        
        public CalculateFatRangeResponseBody() {
        }
        
        public CalculateFatRangeResponseBody(string CalculateFatRangeResult) {
            this.CalculateFatRangeResult = CalculateFatRangeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NutritionAssessmentSoapChannel : TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NutritionAssessmentSoapClient : System.ServiceModel.ClientBase<TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap>, TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap {
        
        public NutritionAssessmentSoapClient() {
        }
        
        public NutritionAssessmentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NutritionAssessmentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NutritionAssessmentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NutritionAssessmentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal CalculateBMI(decimal h, decimal w) {
            return base.Channel.CalculateBMI(h, w);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateBMIAsync(decimal h, decimal w) {
            return base.Channel.CalculateBMIAsync(h, w);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TastyChef.TastyChefNutritionAssessmentWS.weightstatusResponse TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.weightstatus(TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequest request) {
            return base.Channel.weightstatus(request);
        }
        
        public string weightstatus(decimal bmi) {
            TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequestBody();
            inValue.Body.bmi = bmi;
            TastyChef.TastyChefNutritionAssessmentWS.weightstatusResponse retVal = ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).weightstatus(inValue);
            return retVal.Body.weightstatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.weightstatusResponse> TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.weightstatusAsync(TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequest request) {
            return base.Channel.weightstatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.weightstatusResponse> weightstatusAsync(decimal bmi) {
            TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.weightstatusRequestBody();
            inValue.Body.bmi = bmi;
            return ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).weightstatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRResponse TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateBMR(TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequest request) {
            return base.Channel.CalculateBMR(request);
        }
        
        public decimal CalculateBMR(decimal h, decimal w, int age, string gender) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequestBody();
            inValue.Body.h = h;
            inValue.Body.w = w;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRResponse retVal = ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateBMR(inValue);
            return retVal.Body.CalculateBMRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRResponse> TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateBMRAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequest request) {
            return base.Channel.CalculateBMRAsync(request);
        }
        
        public System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRResponse> CalculateBMRAsync(decimal h, decimal w, int age, string gender) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateBMRRequestBody();
            inValue.Body.h = h;
            inValue.Body.w = w;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            return ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateBMRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesResponse TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateCalories(TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequest request) {
            return base.Channel.CalculateCalories(request);
        }
        
        public decimal CalculateCalories(decimal bmr, decimal activity, string weightstatus) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequestBody();
            inValue.Body.bmr = bmr;
            inValue.Body.activity = activity;
            inValue.Body.weightstatus = weightstatus;
            TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesResponse retVal = ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateCalories(inValue);
            return retVal.Body.CalculateCaloriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesResponse> TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateCaloriesAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequest request) {
            return base.Channel.CalculateCaloriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesResponse> CalculateCaloriesAsync(decimal bmr, decimal activity, string weightstatus) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateCaloriesRequestBody();
            inValue.Body.bmr = bmr;
            inValue.Body.activity = activity;
            inValue.Body.weightstatus = weightstatus;
            return ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateCaloriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateResponse TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.levelCarbohydrate(TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequest request) {
            return base.Channel.levelCarbohydrate(request);
        }
        
        public string levelCarbohydrate(string weightstatus, string medical) {
            TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequestBody();
            inValue.Body.weightstatus = weightstatus;
            inValue.Body.medical = medical;
            TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateResponse retVal = ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).levelCarbohydrate(inValue);
            return retVal.Body.levelCarbohydrateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateResponse> TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.levelCarbohydrateAsync(TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequest request) {
            return base.Channel.levelCarbohydrateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateResponse> levelCarbohydrateAsync(string weightstatus, string medical) {
            TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.levelCarbohydrateRequestBody();
            inValue.Body.weightstatus = weightstatus;
            inValue.Body.medical = medical;
            return ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).levelCarbohydrateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeResponse TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateProteinRange(TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequest request) {
            return base.Channel.CalculateProteinRange(request);
        }
        
        public string CalculateProteinRange(string level, decimal calories) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequestBody();
            inValue.Body.level = level;
            inValue.Body.calories = calories;
            TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeResponse retVal = ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateProteinRange(inValue);
            return retVal.Body.CalculateProteinRangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeResponse> TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateProteinRangeAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequest request) {
            return base.Channel.CalculateProteinRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeResponse> CalculateProteinRangeAsync(string level, decimal calories) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateProteinRangeRequestBody();
            inValue.Body.level = level;
            inValue.Body.calories = calories;
            return ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateProteinRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeResponse TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateCarbohydrateRange(TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequest request) {
            return base.Channel.CalculateCarbohydrateRange(request);
        }
        
        public string CalculateCarbohydrateRange(string level, decimal calories) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequestBody();
            inValue.Body.level = level;
            inValue.Body.calories = calories;
            TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeResponse retVal = ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateCarbohydrateRange(inValue);
            return retVal.Body.CalculateCarbohydrateRangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeResponse> TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateCarbohydrateRangeAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequest request) {
            return base.Channel.CalculateCarbohydrateRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeResponse> CalculateCarbohydrateRangeAsync(string level, decimal calories) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateCarbohydrateRangeRequestBody();
            inValue.Body.level = level;
            inValue.Body.calories = calories;
            return ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateCarbohydrateRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeResponse TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateFatRange(TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequest request) {
            return base.Channel.CalculateFatRange(request);
        }
        
        public string CalculateFatRange(string level, decimal calories) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequestBody();
            inValue.Body.level = level;
            inValue.Body.calories = calories;
            TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeResponse retVal = ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateFatRange(inValue);
            return retVal.Body.CalculateFatRangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeResponse> TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap.CalculateFatRangeAsync(TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequest request) {
            return base.Channel.CalculateFatRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeResponse> CalculateFatRangeAsync(string level, decimal calories) {
            TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequest inValue = new TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequest();
            inValue.Body = new TastyChef.TastyChefNutritionAssessmentWS.CalculateFatRangeRequestBody();
            inValue.Body.level = level;
            inValue.Body.calories = calories;
            return ((TastyChef.TastyChefNutritionAssessmentWS.NutritionAssessmentSoap)(this)).CalculateFatRangeAsync(inValue);
        }
        
        public decimal CalculateProtein(decimal calories) {
            return base.Channel.CalculateProtein(calories);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateProteinAsync(decimal calories) {
            return base.Channel.CalculateProteinAsync(calories);
        }
        
        public decimal CalculateFats(decimal calories) {
            return base.Channel.CalculateFats(calories);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateFatsAsync(decimal calories) {
            return base.Channel.CalculateFatsAsync(calories);
        }
        
        public decimal CalculateCarbohydrate(decimal calories) {
            return base.Channel.CalculateCarbohydrate(calories);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateCarbohydrateAsync(decimal calories) {
            return base.Channel.CalculateCarbohydrateAsync(calories);
        }
    }
}
